# Generated by Django 2.2.5 on 2020-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcctapp', '0002_auto_20200709_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='n_images',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='team',
            field=models.IntegerField(null=True),
        ),
    ]
