# Generated by Django 2.2.5 on 2020-07-09 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcctapp', '0003_auto_20200709_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='share',
            field=models.CharField(max_length=100000, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
