# Generated by Django 2.2.5 on 2020-07-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcctapp', '0004_auto_20200709_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagespatient',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
